### ISSUE TITLE
FNA support?

### ISSUE THREAD

**Issue by andreakarasho** [MyraUI/Myra#28]
Hi, i've seen exists a FNA support, but is an old version of myra.
Will is there a support for FNA with latest version of myra?

Thanks :)

**Comment by rds1983** [comment]
Hi,
Thing is since version 4.6 Myra had moved on top of MonoGame.Extended.
It uses TextureAtlases, BitmapFonts and some smaller things.
Before the move Myra had it's own implementation for such things.

So answering your question, since MGE doesnt support FNA, Myra doesnt support it either.
It could be fixed in future. If say MGE starts support FNA. Or Myra may get off MGE and starts using official XNA's SpriteFont.

**Comment by rds1983** [comment]
I've went 2nd way(getting off MGE and using official SpriteFont), so latest Myra (0.6.1) supports FNA. Therefore I am closing this issue.
