### ISSUE TITLE
Why MouseWheelChanged does not fire on grid?

### ISSUE THREAD

**Issue by peon501** [MyraUI/Myra#45]
```
grid.MouseWheelChanged += (s, a) =>
 {
}
```
why MouseWheelChanged does not fire on Grid element?

**Comment by rds1983** [comment]
Thing is MouseWheelChanged requires a widget to be focused at in order to fire(same thing with KeyUp, KeyDown events).
Grid could be tuned following way to catch MouseWheelChanged event:
1. Set grid's CanFocus property to true:
```C#
  _grid.CanFocus = true;
```

2. Make grid focused. It can be done either by clicking on it or programmatically through following code:
```C#
  _desktop.FocusedWidget = _grid;
```

**Comment by rds1983** [comment]
Btw, there is even simplier workaround. Desktop class has full set of input events that fire regardless of what is focused.
So you can simply do following:
```C#
  _desktop.MouseWheelChanged += (s, a) => {
};
```

**Comment by peon501** [comment]
Ty. for the solution. I did like that:
```
            _grid.CanFocus = true;
            _grid.MouseEntered += (s, a) =>
            {
                _host.FocusedWidget = _grid;
            };
           _grid.MouseWheelChanged += (s, a) =>
            {

            };
```
